# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartriges',
            fields=[
                ('comment', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('model', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
                ('type', models.CharField(max_length=255, unique=True, verbose_name='\u0422\u0438\u043f \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
                ('count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0438',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0438',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('disp_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('status', models.CharField(blank=True, default='\u041e\u0442\u043f\u0440\u043f\u0430\u0432\u043a\u0430', max_length=255, null=True, verbose_name='\u0412\u0438\u0434 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_send.Cartriges', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u043f\u0440\u0430\u0432\u043a\u0438-',
                'verbose_name_plural': '\u041e\u0442\u043f\u0440\u0430\u0432\u043a\u0438-',
            },
        ),
        migrations.CreateModel(
            name='PostOffices',
            fields=[
                ('comment', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('index', models.IntegerField(verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0435 \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u041f\u043e\u0447\u0442\u043e\u0432\u043e\u0435 \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCartridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('count', models.IntegerField(verbose_name='\u041a\u043e\u043b\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('date_create_add', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('number_doc', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043d\u0430\u043a\u043b\u0430\u0434\u043d\u043e\u0439')),
                ('status', models.CharField(blank=True, default='\u041f\u0440\u0438\u0445\u043e\u0434', max_length=255, null=True, verbose_name='\u0412\u0438\u0434 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_send.Cartriges', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u0445\u043e\u0434',
                'verbose_name_plural': '\u041f\u0440\u0438\u0445\u043e\u0434',
            },
        ),
        migrations.AddField(
            model_name='dispatch',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_send.PostOffices', verbose_name='\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435'),
        ),
    ]
