# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_send', '0002_auto_20171030_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=255, verbose_name='\u0422\u0438\u043f \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cartriges',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_send.TypeCart', verbose_name='\u0422\u0438\u043f \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430'),
        ),
    ]
